import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Content from "../components/Content";
import Menu from "../components/Menu";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div className=" h-screen overflow-hidden">
      <Head>
        <title>Bryan Kahiga</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex">
        <Menu />
        <Content />
      </main>
    </div>
  );
};

export default Home;
